


(* TEST SECTION UNTIL Q-7 *)
(*
CAR (CONS (INT 1,INT 2)) = INT 1;
CDR (CONS (INT 1,INT 2)) = INT 2;
NULL NIL = T;
NULL (INT 1) = NIL;
INTEGER (INT 1) = T;
INTEGER (STR "A") = NIL;
QUOTE (INT 15) = (INT 15);
LST NIL = T;
LST (CONS (NIL,NIL)) = T;
LST (CONS (INT 1,NIL)) = T;
LST (CONS (INT 1,CONS (NIL,NIL))) = T;
LST (CONS (INT 1,CONS (INT 2,NIL))) = T;
LST (CONS (INT 1,CONS (INT 2,CONS (INT 3,NIL)))) = T;
LST (CONS (CONS (NIL,NIL),NIL)) = T;
LST (CONS (CONS (INT 1,NIL),NIL)) = T;
LST (CONS (CONS (INT 1,CONS (INT 2,NIL)),NIL)) = T;
LST (INT 1) = NIL;
LST (CONS (NIL,INT 1)) = NIL;
LST (CONS (INT 1,INT 1)) = NIL;
LST (CONS (INT 1,CONS (NIL,INT 2))) = NIL;
LST (CONS (INT 1,CONS (INT 2,INT 3))) = NIL;
LST (CONS (INT 1,CONS (INT 2,CONS (INT 3,INT 4)))) = NIL;
LST (CONS (CONS (NIL,INT 1),NIL)) = NIL;
LST (CONS (CONS (INT 1,INT 2),NIL)) = NIL;
LST (CONS (CONS (INT 1,CONS (INT 2,INT 3)),NIL)) = NIL;
EQ (NIL,NIL) = T;
EQ (INT 1,INT 1) = T;
EQ (INT 1,INT 2) = NIL;
EQ (NIL,CONS (NIL,NIL)) = NIL;
EQ (CONS (NIL,INT 3),CONS (NIL,INT 3)) = T;
EQ (CONS (INT 1,INT 3),CONS (NIL,INT 3)) = NIL;
EQ (CONS (NIL,INT 3),CONS (NIL,INT 4)) = NIL;
EQ (CONS (STR "K",CONS (INT 42,NIL)),CONS (STR "K",CONS (INT 42,NIL))) = T;
EQ (CONS (STR "K",CONS (INT 42,NIL)),CONS (STR "K",CONS (INT 43,NIL))) = NIL;
PLUS (INT 40,INT 2) = INT 42;
PLUS (INT 44,INT ~2) = INT 42;
TIMES (INT 21,INT 2) = INT 42;
TIMES (INT ~21,INT ~2) = INT 42;
MEANING (INT 1, INT 2) = NIL;
MEANING (STR "A",NIL) = NIL;
MEANING (STR "A",CONS(STR "A",INT 1)) = NIL;
MEANING (STR "A",CONS (CONS (STR "A",INT 1),NIL)) = INT 1;
MEANING (STR "A",CONS (CONS (INT 1,STR "A"),NIL)) = NIL;
MEANING (STR "A",CONS (CONS (NIL,STR "A"),NIL)) = NIL;
MEANING (STR "A",CONS (CONS (STR "A",NIL),NIL)) = NIL;
MEANING (NIL,CONS (CONS (STR "A",STR "B"),NIL)) = NIL;
MEANING (STR "A",CONS (CONS (STR "B",STR "C"),CONS (CONS (STR "A",STR "D"),NIL))) = STR "D";
MEANING (STR "A",CONS (CONS (STR "A",STR "B"),CONS (CONS (STR "A",STR "C"),NIL))) = STR "B";
MEANING (STR "A",CONS (CONS (STR "B",STR "A"),CONS (CONS (STR "C",STR "A"),NIL))) = NIL;
COND (NIL,NIL,NIL) = NIL;
COND (NIL,NIL,INT 1) = INT 1;
COND (NIL,INT 1,INT 2) = INT 2;
COND (INT 1,INT 2,NIL) = INT 2;
COND (INT 1,NIL,INT 2) = NIL;
*)

(* TEST SECTION FOR Q-8 ONLY*)
(*
(* NOTE: to use these tests you can replace the "==" operator with the EQ function *)
EVAL (NIL,NIL) == NIL;
EVAL ((INT 2),NIL) == INT 2;
EVAL ((CONS (SF (UNARY INTEGER),CONS (INT 1,NIL))),NIL) == T;
EVAL ((CONS (SF (UNARY INTEGER),CONS (STR "A",NIL))),NIL) == NIL;
EVAL ((CONS (SF (BINARY PLUS),CONS (INT 1,CONS (INT 2,NIL)))),NIL) == INT 3;
EVAL ((CONS (SF (BINARY TIMES),CONS (INT 5,CONS (INT 2,NIL)))),NIL) == INT 10;
*)

(* TEST SECTION FOR Q-9 ONLY*)
(*
(* NOTE: to use these tests you can replace the "==" with EQ function *)
EVAL (CONS (EAGER (BINARY PLUS), CONS (INT 5, CONS (INT 7, NIL))), NIL) == INT 12;
EVAL ((CONS (NORMAL (UNARY CAR),CONS (CONS (INT 1, INT 2),NIL))),NIL) == INT 1;
EVAL (CONS (EAGER (BINARY PLUS),
		CONS (INT 5,
		CONS (CONS (NORMAL (UNARY CAR),
				CONS (CONS (INT 3, INT 2),
	NIL)), NIL))), NIL) == INT 8;
EVAL (CONS (EAGER (BINARY TIMES),
		CONS (CONS (NORMAL (UNARY CDR),
				CONS (CONS (INT 2,INT 3),NIL)),
		CONS (CONS (NORMAL (UNARY CAR),
				CONS (CONS (INT 4,INT 5),NIL)),
	NIL))), NIL) == INT 12;
EQ(NORMAL (UNARY (fn a => a)),NORMAL (BINARY (fn (a,b) => a))) == NIL;
EQ(NORMAL (UNARY (fn a => a)),NORMAL (UNARY (fn a => a))) == T;
EQ(NORMAL (UNARY (fn a => a)),EAGER (UNARY (fn a => a))) == NIL;
*)



(* FINAL TESTS *)

print "\n\n~ Test Prepartion ~\n";
infix ===
fun arg1 === arg2 = EQ (arg1,arg2) NIL;
val env = SETQ (STR "C", INT 3) (SETQ (STR "B",INT 2) NIL);
val c = (CONS (NORMAL (UNARY QUOTE),
			CONS (INT 3,NIL)));
val b = (CONS (NORMAL (UNARY QUOTE),
			CONS (INT 2,NIL)));
val d = CONS (NORMAL (UNARY QUOTE),
			CONS (INT 4,NIL));

print "\nAll output should be like this:\n";
INT 1 === INT 1;

print "\n~ STAFF TESTS (except quote) ~\n";
CAR (CONS (INT 5, INT 6)) NIL === INT 5;
CDR (CONS (INT 5, INT 6)) NIL === INT 6;
NULL NIL NIL === STR "T";
NULL (INT 5) NIL === NIL;
INTEGER (INT 1000) NIL === STR "T";
INTEGER (STR "ABC") NIL === NIL;
LST (CONS (CONS(INT 5, NIL), NIL)) NIL === STR "T";
LST (CONS (CONS(INT 5, INT 5), NIL)) NIL === NIL;
(*QUOTE (CONS (EAGER (BINARY PLUS), 
     CONS (INT 5, CONS (INT 7, NIL)))) NIL
	=== CONS (EAGER (BINARY PLUS),CONS (INT 5,CONS (INT 7, NIL)));*)
(*Check this test manually because you dont need to compare function types*)
QUOTE (STR "AB") NIL === STR "AB";
EQ (CONS (STR "A", INT 6), 
        CONS (STR "B", INT 6)) NIL === NIL;
EQ (STR "&", STR "&") NIL === STR "T";
PLUS (INT 5, INT 7) NIL === INT 12;
TIMES (INT 5, INT 7) NIL === INT 35;
MEANING (STR "A", 
      CONS(CONS(STR "A", INT 5), 
      CONS(CONS(STR "B", INT 8), NIL))) NIL === INT 5;
EVAL (CONS (EAGER (BINARY PLUS), 
           CONS (INT 5, CONS (INT 7, NIL))), NIL) === INT 12;
COND(CONS(NORMAL (UNARY QUOTE), 
     CONS(T, NIL)), INT 5, STR "7") 
     (CONS(CONS(STR "7", INT 14), NIL)) === INT 5;
SETQ (STR "B", INT 67) (CONS (CONS (STR "A", INT 56), NIL))
	=== CONS (CONS (STR "B",INT 67),CONS (CONS (STR "A",INT 56),NIL));

print "\n~ TESTS #01 ~\n";
CAR (CONS (INT 1,INT 2)) NIL === INT 1;
CDR (CONS (INT 1,INT 2)) NIL === INT 2;
NULL NIL NIL === T;
NULL (INT 1) NIL === NIL;
INTEGER (INT 1) NIL === T;
INTEGER (STR "A") NIL === NIL;
QUOTE (INT 15) NIL === INT 15;
LST NIL NIL === T;
LST (CONS (NIL,NIL)) NIL === T;
LST (CONS (INT 1,NIL)) NIL === T;
LST (CONS (INT 1,CONS (NIL,NIL))) NIL === T;
LST (CONS (INT 1,CONS (INT 2,NIL))) NIL === T;
LST (CONS (INT 1,CONS (INT 2,CONS (INT 3,NIL)))) NIL === T;
LST (CONS (CONS (NIL,NIL),NIL)) NIL === T;
LST (CONS (CONS (INT 1,NIL),NIL)) NIL === T;
LST (CONS (CONS (INT 1,CONS (INT 2,NIL)),NIL)) NIL === T;

print "\n~ TESTS #02 ~\n";
LST (INT 1) NIL === NIL;
LST (CONS (NIL,INT 1)) NIL === NIL;
LST (CONS (INT 1,INT 1)) NIL === NIL;
LST (CONS (INT 1,CONS (NIL,INT 2))) NIL === NIL;
LST (CONS (INT 1,CONS (INT 2,INT 3))) NIL === NIL;
LST (CONS (INT 1,CONS (INT 2,CONS (INT 3,INT 4)))) NIL === NIL;
LST (CONS (CONS (NIL,INT 1),NIL)) NIL === NIL;
LST (CONS (CONS (INT 1,INT 2),NIL)) NIL === NIL;
LST (CONS (CONS (INT 1,CONS (INT 2,INT 3)),NIL)) NIL === NIL;

print "\n~ TESTS #03 ~\n";
EQ (NIL,NIL) NIL === T;
EQ (INT 1,INT 1) NIL === T;
EQ (INT 1,INT 2) NIL === NIL;
EQ (NIL,CONS (NIL,NIL)) NIL === NIL;
EQ (CONS (NIL,INT 3),CONS (NIL,INT 3)) NIL === T;
EQ (CONS (INT 1,INT 3),CONS (NIL,INT 3)) NIL === NIL;
EQ (CONS (NIL,INT 3),CONS (NIL,INT 4)) NIL === NIL;
EQ (CONS (STR "K",CONS (INT 42,NIL)),CONS (STR "K",CONS (INT 42,NIL))) NIL === T;
EQ (CONS (STR "K",CONS (INT 42,NIL)),CONS (STR "K",CONS (INT 43,NIL))) NIL === NIL;

print "\n~ TESTS #04 ~\n";
PLUS (INT 40,INT 2) NIL === INT 42;
PLUS (INT 44,INT ~2) NIL === INT 42;
TIMES (INT 21,INT 2) NIL === INT 42;
TIMES (INT ~21,INT ~2) NIL === INT 42;

print "\n~ TESTS #05 ~\n";
MEANING (STR "A",NIL) NIL === NIL;
MEANING (STR "A",CONS (CONS (STR "A",INT 1),NIL)) NIL === INT 1;
MEANING (STR "A",CONS (CONS (STR "B",STR "A"),NIL)) NIL === NIL;
MEANING (STR "A",CONS (CONS (STR "A",NIL),NIL)) NIL === NIL;
MEANING (STR "A",CONS (CONS (STR "B",STR "C"),CONS (CONS (STR "A",STR "D"),NIL))) NIL === STR "D";
MEANING (STR "A",CONS (CONS (STR "A",STR "B"),CONS (CONS (STR "A",STR "C"),NIL))) NIL === STR "B";
MEANING (STR "A",CONS (CONS (STR "B",STR "A"),CONS (CONS (STR "C",STR "A"),NIL))) NIL === NIL;

print "\n~ TESTS #06 ~\n";
COND (NIL,NIL,NIL) NIL === NIL;
COND (NIL,NIL,INT 1) NIL === INT 1;
COND (NIL,INT 1,INT 2) NIL === INT 2;
COND (INT 1,INT 2,NIL) NIL === INT 2;
COND (INT 1,NIL,INT 2) NIL === NIL;

print "\n~ TESTS #07 ~\n";
EVAL (NIL,NIL) === NIL;
EVAL ((INT 2),NIL) === INT 2;
EVAL ((CONS (EAGER (UNARY INTEGER),CONS (INT 1,NIL))),NIL) === T;
EVAL ((CONS (EAGER (UNARY INTEGER),CONS (STR "A",NIL))),NIL) === NIL;
EVAL ((CONS (EAGER (BINARY PLUS),CONS (INT 1,CONS (INT 2,NIL)))),NIL) === INT 3;
EVAL ((CONS (EAGER (BINARY TIMES),CONS (INT 5,CONS (INT 2,NIL)))),NIL) === INT 10;

print "\n~ TESTS #08 ~\n";
SETQ (NIL,INT 1) NIL === CONS (CONS (NIL,INT 1),NIL);
COND (CONS(NORMAL (UNARY QUOTE),CONS(T, NIL)),INT 5,STR "7") 
     (CONS(CONS(STR "7", INT 14), NIL))
     === INT 5;
COND (NIL,INT 5,STR "7") 
     (CONS(CONS(STR "7", INT 14), NIL))
     === INT 14;


print "\n~ TESTS #09 ~\n";
EVAL (CONS (EAGER (BINARY PLUS), CONS (INT 5, CONS (INT 7, NIL))), NIL) === INT 12;

print "\n~ TESTS #10 ~\n";
env === CONS (CONS (STR "C",INT 3),CONS (CONS (STR "B",INT 2),NIL));
MEANING (STR "C",env) NIL === INT 3;
MEANING (STR "C",NIL) env === NIL;

print "\n~ TESTS #11 ~\n";
EVAL (CONS (EAGER (BINARY PLUS),
			CONS (b, 
				CONS (b,NIL))),NIL) === INT 4;
EVAL (CONS (EAGER (BINARY TIMES),
			CONS (d, 
				CONS (b,NIL))),NIL) === INT 8;
EVAL (CONS (EAGER (BINARY TIMES),
			CONS (c, 
				CONS (b,NIL))),NIL) === INT 6;
EVAL (CONS (EAGER (TRINARY COND),
			CONS (NIL,
				CONS (b,
					CONS (d,NIL)))
			),NIL) === INT 4;
EVAL (CONS (EAGER (TRINARY COND),
			CONS (b,
				CONS (d,
					CONS (b,NIL)))
			),NIL) === INT 4;

print "\n~ TESTS #12 ~\n";
SETQ (STR "B",b) NIL === CONS (CONS (STR "B",INT 2),NIL);
EVAL (CONS (NORMAL (BINARY SETQ),
			CONS (STR "B", 
				CONS (b,NIL))),NIL)
	=== CONS (CONS (STR "B",INT 2),NIL);
EVAL (CONS (EAGER (BINARY SETQ),
			CONS (STR "B", 
				CONS (STR "C",NIL))),env)
	=== CONS (CONS (INT 2,INT 3),env);

print "\n~ TESTS #13 ~\n";
EVAL (CONS (EAGER (BINARY PLUS),
			CONS (STR "B", 
				CONS (INT 1,NIL))),env)
	=== INT 3;
EVAL (CONS (NORMAL (TRINARY COND),
			CONS (CONS (EAGER (BINARY EQ),CONS (NIL,CONS (INT 1,NIL))),
				CONS (d,
					CONS (b,NIL)))
			),NIL) === INT 2;
EVAL (CONS (NORMAL (TRINARY COND),
			CONS (CONS (EAGER (BINARY PLUS),CONS (INT 3,CONS (INT 3,NIL))),
				CONS (d,
					CONS (b,NIL)))
			),NIL) === INT 4;
EVAL (CONS (NORMAL (TRINARY COND),
			CONS (INT 1,
				CONS (STR "B",
					CONS (c,NIL)))
			),env) === INT 2;
EVAL (CONS (NORMAL (TRINARY COND),
			CONS (NIL,
				CONS (STR "B",
					CONS (STR "C",NIL)))
			),env) === INT 3;

print "\n~ TESTS #14 ~\n";
EVAL (CONS 
	(NORMAL (UNARY QUOTE), 
		CONS (INT 3,NIL))
	,NIL) === INT 3;
(* Following tests will fail if you try to EVAL the wrong argument of COND *)
EVAL (CONS (NORMAL (TRINARY COND),
			CONS (CONS (EAGER (BINARY EQ),CONS (NIL,CONS (INT 1,NIL))),
				CONS (EAGER (BINARY PLUS),
					CONS (b,NIL)))
			),NIL) === INT 2;
EVAL (CONS (NORMAL (TRINARY COND),
			CONS (CONS (EAGER (BINARY PLUS),CONS (INT 3,CONS (INT 3,NIL))),
				CONS (d,
					CONS (EAGER (BINARY PLUS),NIL)))
			),NIL) === INT 4;
